language: rust
rust:
- nightly
before_install:
- openssl aes-256-cbc -K $encrypted_4b7952f4d113_key -iv $encrypted_4b7952f4d113_iv
  -in secure.json.enc -out ~/secure.json -d
deploy:
  provider: gae
  keyfile: "~/secure.json"
  project: test-website
  skip_cleanup: true
