language: rust
rust:
- nightly
before_install:
- openssl aes-256-cbc -K $encrypted_d3ed7a8f1cef_key -iv $encrypted_d3ed7a8f1cef_iv
  -in secure.json.enc -out secure.json -d
deploy:
  provider: gae
  keyfile: ~/secure.json
  project: test-website-202805
  skip_cleanup: true